from typing import Dict, Any, Optional
from pydantic import BaseModel, Field
class StandardFinding(BaseModel):
    id: str = Field(..., description="Unique vulnerability identifier (e.g. OSV-2023-XXXX or CVE-2023-XXXX)")
    title: str = Field(..., description="Short title describing the finding")
    severity: str = Field(..., description="Severity level: CRITICAL, HIGH, MEDIUM, LOW, INFO, UNKNOWN")
    description: str = Field(..., description="Detailed summary of the vulnerability")
    category: Optional[str] = Field(None, description="One of the 16 APK/API weakness categories, or 'Vulnerable Dependency'")
    cause: Optional[str] = Field(None, description="Why the weakness exists (the triggering condition)")
    evidence: list[str] = Field(default_factory=list, description="Supporting evidence snippets / observations")
    affected_component: Optional[str] = Field(None, description="Affected file, class, or manifest component")
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Detection reliability, 0.0-1.0")
    exploitability: Optional[str] = Field(None, description="Exploitability estimation: HIGH, MEDIUM, LOW")
    masvs: list[str] = Field(default_factory=list, description="OWASP MASVS control IDs (e.g. MASVS-STORAGE-1)")
    maswe: list[str] = Field(default_factory=list, description="OWASP MASWE IDs (e.g. MASWE-0005)")
    remediation: Optional[str] = Field(None, description="Recommended fix")
    package_name: Optional[str] = Field(None, description="Affected library/component name")
    version: Optional[str] = Field(None, description="Affected version detected")
    cve: Optional[str] = Field(None, description="Associated CVE ID if available")
    references: list[str] = Field(default_factory=list, description="External reference URLs")
    raw_data: Dict[str, Any] = Field(default_factory=dict, description="Raw response payload from scanner")
